#!/bin/bash
# join rows to get a matrix view
# for molcas files remove rows before and after orbitals 

if [[ $# -lt 2 ]]; then
  echo 'Usage: joinorb <orb-file> "<list of dimensions of each symmetry>"'
  echo 'e.g., joinorb h2o.overlap "11 4 7 2"'
  echo ' or,  joinorb h2o.overlap "11A1  +   4B1  +   7B2  +   2A2"'
  exit
fi
IFS=' ,+' read -ra DIMSRAW <<< "$2"
DIMSY=
for dim in "${DIMSRAW[@]}"; do
  DIMSY="$DIMSY $(echo $dim | grep -oP "^\d*")"
done
awk -F"[, ]+" -v dimstr="$DIMSY" '
BEGIN {
  ndim=split(dimstr,dims," ");
  cdim=1;
  nl=0;
  len=0;
}
#non-empty with a number
(NF>0 && ($1 ~ /^[0-9eE\-\+\.]+$/ || ($1=="" && $2 ~ /^[0-9eE\-\+\.]+$/) ) ){
  for(i=1;i<=NF;i++){
    if ($i!="") { 
      len++; 
      printf "%s ", $i;
    }
  } 
} 
(len>=dims[cdim]) {
  printf "\n";
  nl++;
  if(nl>=dims[cdim]) {
    cdim++;
    if (cdim>ndim) exit;
    nl=0;
  } 
  len=0
}
' "$1"
