#!/bin/bash
# split comma- or space-separated orbital coefficients file to max $NNUM values in a row

awk -F"[, ]" -v nnum=5 '
(NF>0){
  len=0;
  for(i=1;i<=NF;i++){
    if ($i!="") { 
      printf "%s,", $i;
      len++; 
      if (len>=nnum || i==NF){
        printf "\n";
        len=0;
      }
    }
  } 
}
' "$1"
